version: '3.7'

networks:
  internal:

services:
  wise-php-cli:
    container_name: wise-php-cli
    build:
      context: .docker/php-cli
      dockerfile: Dockerfile
    networks:
      internal:
    volumes:
      - ./:/var/www/wise
    depends_on:
      - wise-testing-db
  wise-testing-db:
    image: mysql:5.7
    container_name: wise-testing-db
    cap_add:
      - SYS_NICE
    environment:
      MYSQL_DATABASE: 'wise_test'
      MYSQL_ROOT_PASSWORD: 'root'
    ports:
      - '33066:3306'
    volumes:
      - .docker/db/temp:/var/lib/mysql
      - .docker/db/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      internal:
volumes:
  db:
    driver: local